### ISSUE TITLE
The result of `mt.event0 < now()` or `mt.event0 > now()`  is false

### ISSUE THREAD

**Issue by wenj91** [araddon/qlbridge#226]
Output: false                               T:bool            expr:  mt.event0 < now()
Output: false                               T:bool            expr:  mt.event0 > now()

**Comment by wenj91** [comment]
Is there a bug with step into child of maps ?

**Comment by araddon** [comment]
looking

**Comment by araddon** [comment]
I made an update to the examples to show both of those examples, and changed the default namespacing to allow that to work.
