### ISSUE TITLE
Csv, Json, File Reading & inspecting

### ISSUE THREAD

**Issue by araddon** [araddon/qlbridge#69]
Create a cloud storage file reader https://github.com/lytics/cloudstorage that allows the file-parsing to be pluggable, and the pre-fetching, and supports partitioning api.

* [x] google storage files
* [x] local files
* [x] pluggable per-line parsers

**Comment by araddon** [comment]
closed with https://github.com/araddon/qlbridge/pull/74

**Comment by shimondoodkin** [comment]
lytics removed github.com/lytics/cloudstorage repository

**Comment by araddon** [comment]
whoops, must have been a mistake, will make sure it gets public again.

**Comment by epsniff** [comment]
Sorry @shimondoodkin I forgot it wasn't public.
